### ISSUE TITLE
Support install product value of "bitbucket"

### ISSUE THREAD

**Issue by zjkipping** [toolsplus/nx-forge#123]
The Forge CLI supports the following products via the `install` command:
```
-p, --product [product]          product (Jira, Confluence, Compass, Bitbucket)
```
https://developer.atlassian.com/platform/forge/cli-reference/install/

The `install` command for the nx-forge plugin throws the following error when using 'bitbucket' as a product value:
`Property 'product' does not match the schema. 'bitbucket' should be one of jira,confluence,compass.`

**Comment by zjkipping** [comment]
Can work around for now by opening a terminal in the built dist directory of the forge app and doing the raw forge CLI command.

**Comment by tbinna** [comment]
Thanks for the report @zjkipping. This certainly needs to be fixed. The install executor may actually be one that we can remove because it does not do anything nx-forge specific. Regarding your workaround, you can [use the Forge executor](https://toolsplus.github.io/nx-forge/reference/executors#forge) to run any Forge CLI command in the output directory.
